---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [elasticsearch, elasticsearch-install]

- include: configure.yml
  tags: [elasticsearch, elasticsearch-configure]

- include: plugins.yml
  tags: [elasticsearch, elasticsearch-plugins]

- include: proxy.yml
  when: elasticsearch_proxy
  tags: [elasticsearch, elasticsearch-proxy]

- service: name=elasticsearch state=started enabled=yes
  tags: [elasticsearch]

- name: Make monit to look after elasticsearch
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit/conf.d/elasticsearch
    owner=root group=root mode=644
  when: elasticsearch_monit
  notify: restart monit
